name:                lauth
version:             0.1.0.0
github:              "vahaah/lauth"
license:             BSD3
author:              "Alex Vakhitov"
maintainer:          "alex@vakhitov.dev"
copyright:           "2020 Alex Vakhitov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vahaah/lauth#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lauth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lauth

tests:
  lauth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lauth
